DROP TABLE IF EXISTS replies;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED AlWAYS AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- Таблица запросов
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED AlWAYS AS IDENTITY NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    description VARCHAR(600) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

-- Таблица предметов
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED AlWAYS AS IDENTITY NOT NULL,
  owner_id BIGINT references users(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  is_available boolean NOT NULL,
  request_id BIGINT references requests(id) ON DELETE CASCADE,
  CONSTRAINT pk_item PRIMARY KEY (id)
);

-- Таблица бронирований
CREATE TABLE IF NOT EXISTS bookings (
   id BIGINT GENERATED AlWAYS AS IDENTITY NOT NULL,
   item_id BIGINT REFERENCES items(id) ON DELETE CASCADE NOT NULL,
   user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
   start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   end_date TIMESTAMP  WITHOUT TIME ZONE NOT NULL,
   status VARCHAR(20) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT pk_booking PRIMARY KEY (id)
);

-- Таблица комментариев
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED AlWAYS AS IDENTITY NOT NULL,
    item_id BIGINT REFERENCES items(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    text VARCHAR(600),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

-- Таблица ответов
CREATE TABLE IF NOT EXISTS replies (
    id BIGINT GENERATED AlWAYS AS IDENTITY NOT NULL,
    request_id BIGINT REFERENCES requests(id) ON DELETE CASCADE NOT NULL,
    item_id BIGINT REFERENCES items(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pk_replies PRIMARY KEY (id)
);